### ISSUE TITLE
Invalid commit dates at https://cregit.linuxsources.org

### ISSUE THREAD

**Issue by ramosian-glider** [cregit/cregit#4]
1. Open https://cregit.linuxsources.org/code/4.13/include/linux/uio.h.html
2. Search for `copy_from_iter_full`
3. Hover the cursor over the found token.
4. Notice that the tooltip contains the following data: "Al Viro;2017-45-29"

Month numbers are also invalid in other places on that page.

**Comment by dmgerman** [comment]
Sorry, i completely overlooked this issue when it was submitted. This problem has been addressed with PullRequest #5.
